### PR TITLE
update pde tests after matlab changes

### PR DESCRIPTION
**Pull request by bmcdanie**
update `gold_pde.m` and `gold_coefficients.m` - changes to the MATLAB have broken these scripts.

### CODE REVIEW

**Review by dlg0 — CHANGES_REQUESTED** [review]
what's the deal with the changes to the initial conditions? i thought the `new_md_func` had a default constructor or similar which initializes to zero when the function handles are not supplied? In both cont3 and cont6 these zero functions are all being supplied explicitly?

**Comment by bmcdanie** [comment]
> what's the deal with the changes to the initial conditions? i thought the `new_md_func` had a default constructor or similar which initializes to zero when the function handles are not supplied? In both cont3 and cont6 these zero functions are all being supplied explicitly?

the default isn't zero (unless I'm mistaken) - it's all ones. so, this was producing different initial conditions.

**Comment by dlg0** [comment]
Ah, that indeed could be the case. I did think I'd fixed that at one point such that the default is one, and not zero. Perhaps I put that somewhere else.

**Comment by bmcdanie** [comment]
I'd be happy to make that the default too if that is what you want, I just wasn't sure if other functions were relying on the current default.

**Comment by dlg0** [comment]
and now that I read your reply more carefully, it is indeed the case that I want the default to be one, not zero, which means we do need to specify the zero, as you have. However, you should only need to specify a single dimension as zero, since they are all multiplied together, so that might make the code cleaner?

**Comment by bmcdanie** [comment]
we test them dimension-by-dimension, so (I think) that would still cause a failure. I could modify the multi-d function constructor to copy a single argument across all dimensions if we want?

**Review by dlg0 — APPROVED** [review]

**Pull request merged**
